# 创建 Series 对象

In [7]:
import pandas as pd
import numpy as np

# 创建Series对象, 默认自增索引
s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
# 创建自定义索引
s2 = pd.Series([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"])
print(s2)
# 字典形式
s3 = pd.Series({"a": 1, "b": 2, "c": 3})
print(s3)
# 使用numpy创建Series对象
s4 = pd.Series(np.arange(5))
print(s4)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
dtype: int64
0    0
1    1
2    2
3    3
4    4
dtype: int64

## Series 对象的属性

In [15]:
# s6 = pd.Series(data=[0,1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E', 'F'])
# print(s6)

# 加入列表推导式
s6 = pd.Series(data=[i for i in range(6)], index=[i for i in "ABCDEF"])
print(s6)

# 获取Series对象的 索引列（的值）
print(s6.index)
# 获取Series对象的 值列（的值）
print(s6.values)
# Series支持根据索引获取元素，即Series[索引值]
print(s6["D"])
# 根据索引，修改Series对象的元素值
s6["D"] = 99
print(s6)

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
[0 1 2 3 4 5]
3
A     0
B     1
C     2
D    99
E     4
F     5
dtype: int64

# DataFrame 对象入门

## 创建 DataFrame 对象

In [22]:
# 场景1：通过 字典+列表 来创建DataFrame对象
# 每个键值对 = 1列数据
info = {
    "name": ["水冷哥", "深情哥", "紫琪", "德华"],
    "gender": ["男", "男", "女", "男"],
    "age": [25, 30, 22, 28],
}

# 把上述数据集封装成DataFrame对象
df1 = pd.DataFrame(data=info)
print(df1)

# 场景2：通过 列表 + 元组
#  每个元组 = 1行数据

info = [
    ("刘亦菲", "女", 35),
    ("迪丽热巴", "女", 31),
    ("王志奇", "未知", 66),
]
# columns表示列名
df2 = pd.DataFrame(data=info, columns=["name", "gender", "age"])
print(df2)

# 场景3：通过numpy的ndarray -> pandas DataFrame 的方式实现
arr1 = np.arange(12).reshape(3, 4)
df3 = pd.DataFrame(data=arr1, columns=["a", "b", "c", "d"])
print(df3)

  name gender  age
0  水冷哥      男   25
1  深情哥      男   30
2   紫琪      女   22
3   德华      男   28
   name gender  age
0   刘亦菲      女   35
1  迪丽热巴      女   31
2   王志奇     未知   66
   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

## 学生信息处理

In [54]:
# 生成10名同学，5门功课的成绩，成绩范围40-100
score_df = pd.DataFrame(data=np.random.randint(40, 100, (10, 5)))  # 10行 5列
print(score_df)

# 修改DataFrame对象的列名和索引名
column_names = ["语文", "数学", "英语", "物理", "化学"]
index_names = ["同学" + str(i) for i in range(10)]
score_df.columns = column_names
score_df.index = index_names

# rename函数是实现精确修改，inplace=True表示在原数据上操作
# score_df.rename(
#     columns={0: "AI课程", 1: "大数据课程"}, index={0: "同学0", 1: "同学1"}, inplace=True
# )
print(score_df)

    0   1   2   3   4
0  82  73  85  68  91
1  87  99  45  47  61
2  80  48  47  52  58
3  93  43  66  47  57
4  95  45  51  57  68
5  63  83  98  86  54
6  85  90  96  45  59
7  62  94  62  77  40
8  42  57  89  98  73
9  78  48  46  69  58
     语文  数学  英语  物理  化学
同学0  82  73  85  68  91
同学1  87  99  45  47  61
同学2  80  48  47  52  58
同学3  93  43  66  47  57
同学4  95  45  51  57  68
同学5  63  83  98  86  54
同学6  85  90  96  45  59
同学7  62  94  62  77  40
同学8  42  57  89  98  73
同学9  78  48  46  69  58

## DataFrame的基本属性

In [40]:
# shape 维度：即行列数
print(score_df.shape)

# index 索引
print(score_df.index)

# columns 列名
print(score_df.columns)

# 数据
print(score_df.values)

# 行列转置
print(score_df.T)

(10, 5)
Index(['同学0', '同学1', 2, 3, 4, 5, 6, 7, 8, 9], dtype='object')
Index(['AI课程', '大数据课程', 2, 3, 4], dtype='object')
[[50 67 85 49 91]
 [52 44 99 81 54]
 [70 71 40 70 51]
 [99 40 61 48 75]
 [92 69 44 58 91]
 [58 50 64 71 53]
 [63 40 85 51 92]
 [92 92 41 54 73]
 [44 80 94 71 61]
 [86 77 59 54 89]]
       同学0  同学1   2   3   4   5   6   7   8   9
AI课程    50   52  70  99  92  58  63  92  44  86
大数据课程   67   44  71  40  69  50  40  92  80  77
2       85   99  40  61  44  64  85  41  94  59
3       49   81  70  48  58  71  51  54  71  54
4       91   54  51  75  91  53  92  73  61  89

## DataFrame对象方法

In [57]:
# 查看df对象
print(score_df)

# head(n) 查看前n行数据
# print(score_df.head()) # 默认查看5行
print(score_df.head(3))  # 查看前3行数据

# tail(n) 查看后n行数据
# score_df.tail() # 默认查看5行
print(score_df.tail(3))  # 查看后3行数据

# 3. info() 查看数据详细信息
print(score_df.info())

# 4. describe()，查看对象的描述性统计信息
print(score_df.describe())
"""
4分位：
min（最小值）: 0%
25%: 25%
50%: 50%
75%: 75%
max（最大值）: 100%


min    44.000000  40.000000  40.000000  48.000000  51.000000
25%    53.500000  45.500000  47.750000  51.750000  55.750000
50%    66.500000  68.000000  62.500000  56.000000  74.000000
75%    90.500000  75.500000  85.000000  70.750000  90.500000
max    98.000000  92.000000  90.000000  92.000000  98.000000
"""

     语文  数学  英语  物理  化学
同学0  82  73  85  68  91
同学1  87  99  45  47  61
同学2  80  48  47  52  58
同学3  93  43  66  47  57
同学4  95  45  51  57  68
同学5  63  83  98  86  54
同学6  85  90  96  45  59
同学7  62  94  62  77  40
同学8  42  57  89  98  73
同学9  78  48  46  69  58
     语文  数学  英语  物理  化学
同学0  82  73  85  68  91
同学1  87  99  45  47  61
同学2  80  48  47  52  58
     语文  数学  英语  物理  化学
同学7  62  94  62  77  40
同学8  42  57  89  98  73
同学9  78  48  46  69  58
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 同学0 to 同学9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int64
 1   数学      10 non-null     int64
 2   英语      10 non-null     int64
 3   物理      10 non-null     int64
 4   化学      10 non-null     int64
dtypes: int64(5)
memory usage: 480.0+ bytes
None
              语文         数学        英语         物理         化学
count  10.000000  10.000000  10.00000  10.000000  10.000000
mean   76.700000  68.000000  68.50000  64.600000  61.900000
std    16.411717  22.226111  21.58832  18.191573  13.386975
min    42.000000  43.000000  45.00000  45.000000  40.000000
25%    66.750000  48.000000  48.00000  48.250000  57.250000
50%    81.000000  65.000000  64.00000  62.500000  58.500000
75%    86.500000  88.250000  88.00000  75.000000  66.250000
max    95.000000  99.000000  98.00000  98.000000  91.000000

'\n4分位：\nmin（最小值）: 0%\n25%: 25%\n50%: 50%\n75%: 75%\nmax（最大值）: 100%\n\n\nmin    44.000000  40.000000  40.000000  48.000000  51.000000\n25%    53.500000  45.500000  47.750000  51.750000  55.750000\n50%    66.500000  68.000000  62.500000  56.000000  74.000000\n75%    90.500000  75.500000  85.000000  70.750000  90.500000\nmax    98.000000  92.000000  90.000000  92.000000  98.000000\n'

In [63]:
# 5 reset_index() 重置索引列
# print(score_df.reset_index()) # drop=False，默认值，不删除原索引列，将原索引列作为新列，默认列名是index
print(score_df.reset_index(drop=True))  # 删除原索引列，返回新的DataFrame对象

# 6 set_index() 重新设置索引
# score_df.set_index("语文") # 语文列充当索引列

score_df.set_index(["语文", "数学"]) # 语文、数学列充当索引列

   语文  数学  英语  物理  化学
0  82  73  85  68  91
1  87  99  45  47  61
2  80  48  47  52  58
3  93  43  66  47  57
4  95  45  51  57  68
5  63  83  98  86  54
6  85  90  96  45  59
7  62  94  62  77  40
8  42  57  89  98  73
9  78  48  46  69  58

       英语  物理  化学
语文 数学
82 73  85  68  91
87 99  45  47  61
80 48  47  52  58
93 43  66  47  57
95 45  51  57  68
63 83  98  86  54
85 90  96  45  59
62 94  62  77  40
42 57  89  98  73
78 48  46  69  58

# Pandas中的数据类型

In [69]:
# 把上述数据集封装成DataFrame对象
from os import name

# Python中的NONE -> Pandas中的NAN、NaN、nan
df = pd.DataFrame(
    {
        "name": [np.nan, "深情哥", "紫琪", "德华"],
        "gender": ["男", "男", "女", "男"],
        "age": [25, 30, 22, np.nan],
    }
)

print(df)
df1.info()  # s对象没有info()方法

  name gender   age
0  NaN      男  25.0
1  深情哥      男  30.0
2   紫琪      女  22.0
3   德华      男   NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   gender  4 non-null      object
 2   age     4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [78]:
# 演示日期类型datetime
df2 = pd.DataFrame(['2025-03-25','2025-03-26','2025-03-27'], dtype='datetime64[ns]')
print(df2)
print(df2.dtypes)

# 演示日期类型timedelta
startDate = pd.to_datetime('2025-03-25')
endDate = pd.to_datetime('2025-03-27')
day = startDate - endDate
print(day)
print(type(day))


# 创建一个category类型的Series
categories = pd.Series(["apple", "banana", "apple", "orange"], dtype="category")
print(categories)

           0
0 2025-03-25
1 2025-03-26
2 2025-03-27
0    datetime64[ns]
dtype: object
-2 days +00:00:00
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>
0     apple
1    banana
2     apple
3    orange
dtype: category
Categories (3, object): ['apple', 'banana', 'orange']

# pandas基本数据操作

In [98]:
data = pd.read_csv("./data/stock_day.csv")
print(data)

# 移除不需要的列
data.drop(columns=["ma5", "ma10", "ma20"], axis=0, inplace=True)  # 0表示列，1表示行
print(data)

             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

               ma5    ma10    ma20      v_ma5     v_ma10     v_ma20  turnover
2018-02-27  22.942  22.142  22.875   53782.64   46738.65   55576.11      2.39
2018-02-26  22.406  21.955  22.942   40827.52   42736.34   56007.50      1.53
2018-02-23  21.938  21.929  23.022   35119.58   41871.97   56372.85      1.32
2018-02-22  21.446  21.909  23.137   35397.58   39904.78   60149.60      0.90
2018-02-14  21.366  21.923  23.253   33590.21   42935.74   61716.11      0.58
...            ...     ...     ...        ...        ...        ...       ...
2015-03-06  13.112  13.112  13.112  115090.18  115090.18  115090.18      6.16
2015-03-05  12.820  12.820  12.820   98904.79   98904.79   98904.79      3.19
2015-03-04  12.707  12.707  12.707  100812.93  100812.93  100812.93      2.30
2015-03-03  12.610  12.610  12.610  117681.67  117681.67  117681.67      4.76
2015-03-02  12.520  12.520  12.520   96291.73   96291.73   96291.73      3.30

[643 rows x 14 columns]
             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

                v_ma5     v_ma10     v_ma20  turnover
2018-02-27   53782.64   46738.65   55576.11      2.39
2018-02-26   40827.52   42736.34   56007.50      1.53
2018-02-23   35119.58   41871.97   56372.85      1.32
2018-02-22   35397.58   39904.78   60149.60      0.90
2018-02-14   33590.21   42935.74   61716.11      0.58
...               ...        ...        ...       ...
2015-03-06  115090.18  115090.18  115090.18      6.16
2015-03-05   98904.79   98904.79   98904.79      3.19
2015-03-04  100812.93  100812.93  100812.93      2.30
2015-03-03  117681.67  117681.67  117681.67      4.76
2015-03-02   96291.73   96291.73   96291.73      3.30

[643 rows x 11 columns]

## 索引操作

In [99]:
# 先列后行，没有先行后列的取值方式
print(data['open']) # Series
print(data["open"][0])  # 23.53

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
2018-02-14    21.49
              ...
2015-03-06    13.17
2015-03-05    12.88
2015-03-04    12.80
2015-03-03    12.52
2015-03-02    12.25
Name: open, Length: 643, dtype: float64
23.53

In [94]:
# loc索引：行索引和列名来获取元素
print(data.loc["2018-02-27", "open"])  # 23.53

# print(data.loc["2018-02-27":"2018-02-14", :]) # :表示所有列
print(data.loc["2018-02-27":"2018-02-14", ["open", "high"]])


# iloc索引：行号和列索引来获取元素
print(data.iloc[0, 0])  # 23.53
print(data.iloc[0:4, 0:5]) # 第0行到第3行，第0列到第4列

23.53
             open   high
2018-02-27  23.53  25.88
2018-02-26  22.80  23.78
2018-02-23  22.88  23.37
2018-02-22  22.25  22.76
2018-02-14  21.49  21.99
23.53
             open   high  close    low    volume
2018-02-27  23.53  25.88  24.16  23.53  95578.03
2018-02-26  22.80  23.78  23.53  22.80  60985.11
2018-02-23  22.88  23.37  22.82  22.71  52914.01
2018-02-22  22.25  22.76  22.28  22.02  36105.01

In [96]:
# 赋值操作
# data['open'] = 23
# data.low = 3
# print(data)

# 排序操作

In [113]:
# 基于open列进行排序
print(data.sort_values(by="open", ascending=True)) # 升序

# 基于open列进行降序，再基于high列进行降序
print(data.sort_values(by=["open", "high"], ascending=[False, False]))

             open   high  close    low     volume  price_change  p_change  \
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62
2015-09-02  12.30  14.11  12.36  12.30   70201.74         -1.10     -8.17
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
...           ...    ...    ...    ...        ...           ...       ...
2015-06-11  33.17  34.98  34.39  32.51  173075.73          0.54      1.59
2017-11-01  33.85  34.34  33.83  33.10  232325.30         -0.61     -1.77
2015-06-10  34.10  36.35  33.85  32.23  269033.12          0.51      1.53
2015-06-12  34.69  35.98  35.21  34.01  159825.88          0.82      2.38
2015-06-15  34.99  34.99  31.69  31.69  199369.53         -3.52    -10.00

                v_ma5     v_ma10     v_ma20  turnover
2015-03-02   96291.73   96291.73   96291.73      3.30
2015-09-02   96977.99   98537.72  104567.25      2.40
2015-03-03  117681.67  117681.67  117681.67      4.76
2015-03-04  100812.93  100812.93  100812.93      2.30
2015-03-05   98904.79   98904.79   98904.79      3.19
...               ...        ...        ...       ...
2015-06-11  193141.45  151337.71  151428.57      5.92
2017-11-01  353499.64  346829.10  233701.92      5.81
2015-06-10  176305.53  152266.76  149078.50      9.21
2015-06-12  197248.25  154480.41  153888.00      5.47
2015-06-15  201148.55  164608.26  158362.17      6.82

[643 rows x 11 columns]
             open   high  close    low     volume  price_change  p_change  \
2015-06-15  34.99  34.99  31.69  31.69  199369.53         -3.52    -10.00
2015-06-12  34.69  35.98  35.21  34.01  159825.88          0.82      2.38
2015-06-10  34.10  36.35  33.85  32.23  269033.12          0.51      1.53
2017-11-01  33.85  34.34  33.83  33.10  232325.30         -0.61     -1.77
2015-06-11  33.17  34.98  34.39  32.51  173075.73          0.54      1.59
...           ...    ...    ...    ...        ...           ...       ...
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-09-02  12.30  14.11  12.36  12.30   70201.74         -1.10     -8.17
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

                v_ma5     v_ma10     v_ma20  turnover
2015-06-15  201148.55  164608.26  158362.17      6.82
2015-06-12  197248.25  154480.41  153888.00      5.47
2015-06-10  176305.53  152266.76  149078.50      9.21
2017-11-01  353499.64  346829.10  233701.92      5.81
2015-06-11  193141.45  151337.71  151428.57      5.92
...               ...        ...        ...       ...
2015-03-05   98904.79   98904.79   98904.79      3.19
2015-03-04  100812.93  100812.93  100812.93      2.30
2015-03-03  117681.67  117681.67  117681.67      4.76
2015-09-02   96977.99   98537.72  104567.25      2.40
2015-03-02   96291.73   96291.73   96291.73      3.30

[643 rows x 11 columns]

In [116]:
# 按照索引排序
print(data.sort_index(ascending=True))

# Series对象也有排序方法
# print(data.open.sort_index(ascending=True)) # 对open列的索引进行排序
print(data.open.sort_values(ascending=True)) # 对open列的值进行排序

             open   high  close    low     volume  price_change  p_change  \
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
...           ...    ...    ...    ...        ...           ...       ...
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68

                v_ma5     v_ma10     v_ma20  turnover
2015-03-02   96291.73   96291.73   96291.73      3.30
2015-03-03  117681.67  117681.67  117681.67      4.76
2015-03-04  100812.93  100812.93  100812.93      2.30
2015-03-05   98904.79   98904.79   98904.79      3.19
2015-03-06  115090.18  115090.18  115090.18      6.16
...               ...        ...        ...       ...
2018-02-14   33590.21   42935.74   61716.11      0.58
2018-02-22   35397.58   39904.78   60149.60      0.90
2018-02-23   35119.58   41871.97   56372.85      1.32
2018-02-26   40827.52   42736.34   56007.50      1.53
2018-02-27   53782.64   46738.65   55576.11      2.39

[643 rows x 11 columns]
2015-03-02    12.25
2015-09-02    12.30
2015-03-03    12.52
2015-03-04    12.80
2015-03-05    12.88
              ...
2015-06-11    33.17
2017-11-01    33.85
2015-06-10    34.10
2015-06-12    34.69
2015-06-15    34.99
Name: open, Length: 643, dtype: float64

# DataFrame的运算

In [117]:
# 对close列的每个元素进行加2操作
data["close"] + 2 
# data.close.add(2) # 效果同上
print(data)

# 针对low列的每个元素进行减10操作
data["low"] - 10
# data.low.sub(10) # 效果同上
print(data)

             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

                v_ma5     v_ma10     v_ma20  turnover
2018-02-27   53782.64   46738.65   55576.11      2.39
2018-02-26   40827.52   42736.34   56007.50      1.53
2018-02-23   35119.58   41871.97   56372.85      1.32
2018-02-22   35397.58   39904.78   60149.60      0.90
2018-02-14   33590.21   42935.74   61716.11      0.58
...               ...        ...        ...       ...
2015-03-06  115090.18  115090.18  115090.18      6.16
2015-03-05   98904.79   98904.79   98904.79      3.19
2015-03-04  100812.93  100812.93  100812.93      2.30
2015-03-03  117681.67  117681.67  117681.67      4.76
2015-03-02   96291.73   96291.73   96291.73      3.30

[643 rows x 11 columns]
             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

                v_ma5     v_ma10     v_ma20  turnover
2018-02-27   53782.64   46738.65   55576.11      2.39
2018-02-26   40827.52   42736.34   56007.50      1.53
2018-02-23   35119.58   41871.97   56372.85      1.32
2018-02-22   35397.58   39904.78   60149.60      0.90
2018-02-14   33590.21   42935.74   61716.11      0.58
...               ...        ...        ...       ...
2015-03-06  115090.18  115090.18  115090.18      6.16
2015-03-05   98904.79   98904.79   98904.79      3.19
2015-03-04  100812.93  100812.93  100812.93      2.30
2015-03-03  117681.67  117681.67  117681.67      4.76
2015-03-02   96291.73   96291.73   96291.73      3.30

[643 rows x 11 columns]

In [119]:
# 逻辑运算符

# 筛选出open列大于23的值
data[data.open > 23]

# 筛选出open列大于23且close列小于25的值
data[(data.open > 23) & (data.close < 25)]

,open,high,close,low,volume,price_change,p_change,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,77485.53,84805.23,92943.35,0.81
2018-01-29,24.40,24.63,23.77,23.72,65469.81,-0.73,-2.98,91842.60,91692.73,93456.22,1.64
...,...,...,...,...,...,...,...,...,...,...,...
2015-07-01,25.00,25.80,23.27,22.80,124199.99,-1.74,-6.96,145420.94,116819.01,142739.00,4.25
2015-06-29,26.50,26.98,23.83,22.82,168452.12,-1.45,-5.74,123192.98,122196.88,138338.64,5.77
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,100396.01,90830.02,97087.92,2.84
2015-04-16,24.63,25.21,22.97,21.94,221070.31,-1.41,-5.78,182172.04,153247.63,124317.19,7.57
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,174581.78,138001.54,119340.61,8.57

In [ ]:
# 可以通过query函数优化上面的代码
data.query("open > 23 and close < 25")

,open,high,close,low,volume,price_change,p_change,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,77485.53,84805.23,92943.35,0.81
2018-01-29,24.40,24.63,23.77,23.72,65469.81,-0.73,-2.98,91842.60,91692.73,93456.22,1.64
...,...,...,...,...,...,...,...,...,...,...,...
2015-07-01,25.00,25.80,23.27,22.80,124199.99,-1.74,-6.96,145420.94,116819.01,142739.00,4.25
2015-06-29,26.50,26.98,23.83,22.82,168452.12,-1.45,-5.74,123192.98,122196.88,138338.64,5.77
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,100396.01,90830.02,97087.92,2.84
2015-04-16,24.63,25.21,22.97,21.94,221070.31,-1.41,-5.78,182172.04,153247.63,124317.19,7.57
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,174581.78,138001.54,119340.61,8.57

In [126]:
# 固定值的筛选，isin
# data[(data.open == 23.53) | (data.open == 23.67)]
# data.query("open in [23.53, 23.67]")
data[data.open.isin([23.53, 23.67])]

,open,high,close,low,volume,price_change,p_change,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,53782.64,46738.65,55576.11,2.39
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,102925.87,85432.61,65928.23,1.21
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,130237.86,140918.73,160464.67,2.76
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,66728.10,68518.08,68161.18,3.74

## 统计函数

In [134]:
# 查看DataFrame的统计信息
print(data.describe()) 

# 对每列进行求和
print(data.sum())
# 对open列进行求和
print(data.open.sum()) 
print(data.mean()) # 均值
print(data.median()) # 中位数
print(data.cumsum()) # 累计和

             open        high       close         low         volume  \
count  643.000000  643.000000  643.000000  643.000000     643.000000
mean    21.272706   21.900513   21.336267   20.771835   99905.519114
std      3.930973    4.077578    3.942806    3.791968   73879.119354
min     12.250000   12.670000   12.360000   12.200000    1158.120000
25%     19.000000   19.500000   19.045000   18.525000   48533.210000
50%     21.440000   21.970000   21.450000   20.980000   83175.930000
75%     23.400000   24.065000   23.415000   22.850000  127580.055000
max     34.990000   36.350000   35.210000   34.010000  501915.410000

       price_change    p_change          v_ma5         v_ma10         v_ma20  \
count    643.000000  643.000000     643.000000     643.000000     643.000000
mean       0.018802    0.190280  100008.642691  100287.542177  100797.518398
std        0.898476    4.079698   62761.578326   56759.082060   50101.575639
min       -3.520000  -10.030000   10804.740000   19130.510000   23311.000000
25%       -0.390000   -1.850000   55794.985000   59861.955000   64103.675000
50%        0.050000    0.260000   86133.330000   89234.970000   96291.730000
75%        0.455000    2.305000  127655.655000  124693.255000  124001.015000
max        3.030000   10.030000  404443.540000  360028.160000  269280.790000

         turnover
count  643.000000
mean     2.936190
std      2.079375
min      0.040000
25%      1.360000
50%      2.500000
75%      3.915000
max     12.560000
open               13678.35
high               14082.03
close              13719.22
low                13356.29
volume          64239248.79
price_change          12.09
p_change             122.35
v_ma5           64305557.25
v_ma10          64484889.62
v_ma20          64812804.33
turnover            1887.97
dtype: float64
13678.35
open                21.272706
high                21.900513
close               21.336267
low                 20.771835
volume           99905.519114
price_change         0.018802
p_change             0.190280
v_ma5           100008.642691
v_ma10          100287.542177
v_ma20          100797.518398
turnover             2.936190
dtype: float64
open               21.44
high               21.97
close              21.45
low                20.98
volume          83175.93
price_change        0.05
p_change            0.26
v_ma5           86133.33
v_ma10          89234.97
v_ma20          96291.73
turnover            2.50
dtype: float64
                open      high     close       low       volume  price_change  \
2018-02-27     23.53     25.88     24.16     23.53     95578.03          0.63
2018-02-26     46.33     49.66     47.69     46.33    156563.14          1.32
2018-02-23     69.21     73.03     70.51     69.04    209477.15          1.86
2018-02-22     91.46     95.79     92.79     91.06    245582.16          2.22
2018-02-14    112.95    117.78    114.71    112.54    268913.20          2.66
...              ...       ...       ...       ...          ...           ...
2015-03-06  13627.90  14029.93  13667.94  13306.09  63843629.62         11.13
2015-03-05  13640.78  14043.38  13681.10  13318.96  63936810.01         11.39
2015-03-04  13653.58  14056.30  13694.00  13331.57  64003885.45         11.59
2015-03-03  13666.10  14069.36  13706.70  13344.09  64142957.06         11.77
2015-03-02  13678.35  14082.03  13719.22  13356.29  64239248.79         12.09

            p_change        v_ma5       v_ma10       v_ma20  turnover
2018-02-27      2.68     53782.64     46738.65     55576.11      2.39
2018-02-26      5.70     94610.16     89474.99    111583.61      3.92
2018-02-23      8.12    129729.74    131346.96    167956.46      5.24
2018-02-22      9.76    165127.32    171251.74    228106.06      6.14
2018-02-14     11.81    198717.53    214187.48    289822.17      6.72
...              ...          ...          ...          ...       ...
2015-03-06    114.70  63891866.13  64071198.50  64399113.21   1874.42
2015-03-05    116.72  63990770.92  64170103.29  64498018.00   1877.61
2015-03-04    118.29  64091583.85  64270916.22  64598830.93   1879.91
2015-03-03    119.73  64209265.52  64388597.89  64716512.60   1884.67
2015-03-02    122.35  64305557.25  64484889.62  64812804.33   1887.97

[643 rows x 11 columns]

## 自定义函数

In [137]:
# 定义一个对列，最大值-最小值的函数
data[['open','close']].apply(lambda x: x.max() - x.min(),axis=0)

open     22.74
close    22.85
dtype: float64